[package]
name = "cirno"
version = "1.0.2"
description = 'a "smartest" task scheduler'
edition = "2021"

[dependencies]
clap = { version = "4.5.2", features = ["derive"] }
rustix = { version = "0.38.31", features = ["process", "param"] }
sysinfo = "0.30.7"
uuid = { version = "1.7.0", features = ["v1", "std", "fast-rng"] }

[profile.release]
# use lto to optimize the binary
lto = true
